# -*- coding: utf-8 -*-
"""Player_Shooting.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TdwNXVSym-wgQRtxoHhpO64lQzT5tMKf

## Scraping Shooting Stats
"""

# import required packages
from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd

columns = ['Player','Pos','Age', 'Tm','G', 'MP','FG%','Dist.','\xa0','2P','0-3','3-10','10-16','16-3P','3P', '\xa0',
           '2P','0-3','3-10','10-16','16-3P','3P','\xa0','2P','3P','\xa0','%FGA','#','\xa0','%3PA','3P%','\xa0','Att.','#']

col= ['Player','Pos','Age', 'Tm','G', 'MP','FG%','Dist.','\xa0','2P','0-3','3-10','10-16','16-3P','3P', '\xa0',
           '2P','0-3','3-10','10-16','16-3P','3P','\xa0','2P','3P','\xa0','%FGA','#','\xa0','%3PA','3P%','\xa0','Att.','#','Year']

# NBA season we will be analyzing
years = []
for i in range(1997, 2019):
  years.append(i)

final_shooting_stats = pd.DataFrame(columns=col)
for year in years:
  # URL page we will scraping
  url = 'https://www.basketball-reference.com/leagues/NBA_{}_shooting.html'.format(year)

  # this is the HTML from the given URL
  html = urlopen(url)
  soup = BeautifulSoup(html)

  # avoid the first header row
  rows = soup.findAll('tr')[1:]
  player_shots = [[td.getText() for td in rows[i].findAll('td')]
              for i in range(len(rows))]
  #print(player_stats)
  #data.append(player_stats)
  #print(str(player_stats[0]))
  stats = pd.DataFrame(player_shots, columns = columns)
  stats['Year'] = year
  #print(stats)
  final_shooting_stats = pd.concat([final_shooting_stats, stats], ignore_index=True)
  #final_stats = pd.concat(stats, ignore_index=True)

final_shooting_stats.dropna(subset=['Player'], inplace=True)

final_shooting_stats.to_csv (r'player_shooting_stats.csv', index = False, header=True)